---
title: "Bellabeat Fitness Case Study"
author: "Dennis Rotich"
date: "2022-07-22"
output:
  html_document:
    theme: journal
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
---
# Introduction

Bellabeat is a high-tech company that manufactures health-focused smart products including Bellabeat app, Leaf, Time and Spring. It also offers a subscription-based membership program for users giving them access to personalised guidance on having a healthy lifestyle. Bellabeat has positioned itself as a tech-driven wellness company for women.

Bellabeat has been investing extensively on digital marketing including Google Search and being active on social media platforms. The co-founder Sršen knows that an analysis of Bellabeat’s available consumer data would reveal more opportunities for growth.

# Statement of business task
Smart devices are a big part of people’s everyday life. As a smart device manufacturer, Bellabeat can benefit from learning the trend of smart device usage and make data-driven business strategies to explore opportunities for growth.
Key stakeholders:

Urška Sršen: Bellabeat’s cofounder and Chief Creative Officer
Sando Mur: Mathematician and Bellabeat’s co-founder; key member of the Bellabeat executive team
Good starting points would be:

Investigating the products that have similar functionality
Drill down to explore user behaviors when using the product in order to identify any usage trends
Apply the trend on Bellabeat products to identify recommendations on functionality and marketing strategies
Insights from the investigation can help Bellabeat to identify weaknesses of their products and new functions or even inspire ideas on new products.

It can also help to inform marketing strategies like knowing the segment of the age group that is the most active user of smart devices, then Bellabeat can invest in focusing on a specific age group when doing marketing campaigns in the future.

# Prepare the data
The data used in this analysis is the Fitbit Fitness Tracker Data made available by Mobius stored on Kaggle.
This dataset is under CC0: Public Domain license meaning the creator has waive his right to the work under the copyright law.
The data contains personal fitness tracker from thirty fitbit users. Thirty eligible Fitbit users consented to the submission of personal tracker data, including minute-level output for physical activity, heart rate, and sleep monitoring. It includes information about daily activity, steps, and heart rate that can be used to explore users’ habits.
These datasets were generated by respondents to a distributed survey via Amazon Mechanical Turk between 03.12.2016-05.12.2016.
The dataset has in total 18 files in .csv format organized in long format.

#### ROCCC analysis

* Reliability : LOW – dataset was collected from 30 individuals whose gender is unknown.
* Originality : LOW – third party data collect using Amazon Mechanical Turk.
* Comprehensive : MEDIUM – dataset contains multiple fields on daily activity intensity, calories used, daily steps taken, daily sleep time and weight record.
* Current : MEDIUM – data is 5 years old but the habit of how people live does not change over a few years
* Cited : HIGH – data collector and source is well documented

#### Data selection
Focus is on daily usage of the Fitbit device as it should provide a high-level insight on the usage pattern of smart devices. Thus the following files from the dataset has been selected:

* dailyActivity_merged.csv
* dailyCalories_merged.csv
* dailyIntensities_merged.csv
* dailySteps_merged.csv
* sleepDay_merged.csv
* weightLogInfo_merged.csv

# Process the data
Google spreadsheet and Google BigQuery will be used to process the data as the tool functionality fits the purpose.
We will install some tidyverse packages to make our analysis a smooth one
library(tidyverse)
library(dplyr)
library(ggplot2)
library(skimr)
library(tidyr)
library(janitor)
library(lubridate)

# Data cleaning
sleepDay_merged.csv and weightLogInfo_merged.csv are loaded into Google sheet for data cleaning. The fields “SleepDay” and “Date” were not correctly formatted. The following steps has been done:

The date column has been select and format to ‘Date’ using spreadsheet function
Time in the column has been removed as time is irrelevant in this analysis
AM/PM indicator is also removed. 

# Visualization
#### Activity level and calories burnt relation


``` {r}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(tidyr)
library(lubridate)
ggplot (data = Activity_Vs_Calories, mapping = aes(x = SedentaryMinutes, y = Calories)) + geom_point(color='orange')
```

#### Activity level and Sleep burnt relation

```
ggplot (data = Activity_Vs_Sleep, mapping = aes(x = SedentaryMinutes, y = Calories)) + geom_point(color='orange')
```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
